# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bibl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_bibl(object):
    
    def loaddata(self):
        connection = sqlite3.connect('bibla.db')
        qur = "SELECT * FROM books"
        result = connection.execute(qur)
        
        self.tableWidget_1.setRowCount(1)
        for row_number, row_data in enumerate(result):
            self.tableWidget_1.insertRow(row_number)
           
            kik = row_number
            for column_number, data in enumerate(row_data):
                self.tableWidget_1.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
        connection.close()


    def search(self):
        inv = self.lineEdit_8.text()        
        req = self.lineEdit_8.text()
        conn = sqlite3.connect('bibla.db')
        cursor = conn.cursor()
        if self.radioButton_4.isChecked(): 
            inv = int(inv)
            query = "SELECT * FROM books WHERE inv = ?"
            ins = cursor.execute(query,(inv,))
            print('kuk')
        if self.radioButton_3.isChecked():
            query = "SELECT * FROM books WHERE author = ?"
            ins = cursor.execute(query,(req,))
        if self.radioButton_2.isChecked():
            query = "SELECT * FROM books WHERE jenre = ?"
            ins = cursor.execute(query,(req,))
        if self.radioButton_1.isChecked():
            query = "SELECT * FROM books WHERE name = ?"
            ins = cursor.execute(query,(req,))
        self.tableWidget_1.setRowCount(0)
        for row_number, row_data in enumerate(ins):
            self.tableWidget_1.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget_1.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
        conn.close()
        self.tableWidget_1.update()
        conn.close()

    def delete(self):
        inv = self.lineEdit_8.text()
        inv = int(inv)
        conn = sqlite3.connect('bibla.db')
        cursor = conn.cursor()
        ins = cursor.execute("DELETE FROM books WHERE inv = ?",(inv,))
        conn.commit()
        self.tableWidget_1.update()
        self.tableWidget_1.setRowCount(0)
        self.loaddata()
        cursor.close()


    def save(self):
        name = self.lineEdit_1.text()
        jenre = self.lineEdit_2.text()
        ypub = self.lineEdit_3.text()
        ypub = int(ypub)
        author = self.lineEdit_4.text()
        izd = self.lineEdit_5.text()
        num = self.lineEdit_6.text()
        num = int(num)
        conn = sqlite3.connect('bibla.db')
        cursor = conn.cursor()
        ins = cursor.execute("INSERT INTO books (name, jenre, ypub, author, izd, num) VALUES (?, ?,?,?,?,?)",(name,jenre,ypub, author, izd, num))
        conn.commit()
        self.tableWidget_1.update()
        self.tableWidget_1.setRowCount(0)
        self.loaddata()
        cursor.close()


    def clear_fil(self):
        self.lineEdit_1.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_8.clear()


    def setupUi(self, bibl):
        bibl.setObjectName("bibl")
        bibl.resize(848, 495)
        bibl.setMinimumSize(QtCore.QSize(848, 495))
        bibl.setMaximumSize(QtCore.QSize(848, 495))
        self.tableWidget_1 = QtWidgets.QTableWidget(bibl)
        self.tableWidget_1.setGeometry(QtCore.QRect(10, 10, 828, 240))
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(7)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, item)
        self.tableWidget_1.verticalHeader().setVisible(False)
        self.radioButton_1 = QtWidgets.QRadioButton(bibl)
        self.radioButton_1.setGeometry(QtCore.QRect(110, 270, 82, 17))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_1.click()
        self.radioButton_2 = QtWidgets.QRadioButton(bibl)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 300, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(bibl)
        self.radioButton_3.setGeometry(QtCore.QRect(110, 330, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit_8 = QtWidgets.QLineEdit(bibl)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 313, 131, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_1 = QtWidgets.QPushButton(bibl)
        self.pushButton_1.setGeometry(QtCore.QRect(400, 313, 75, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(bibl)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 313, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(bibl)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 313, 101, 23))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_3.setToolTip("Чтобы удалить введите инвентарный номер")
        self.pushButton_3.setToolTipDuration(0)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayoutWidget = QtWidgets.QWidget(bibl)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 400, 811, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 4, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 5, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(bibl)
        self.label_7.setGeometry(QtCore.QRect(20, 315, 81, 16))
        self.label_7.setObjectName("label_7")
        self.radioButton_4 = QtWidgets.QRadioButton(bibl)
        self.radioButton_4.setGeometry(QtCore.QRect(110, 360, 141, 16))
        self.radioButton_4.setObjectName("radioButton_4")

        header = self.tableWidget_1.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        #asd = self.tableWidget_1.hoirzontalHeader()
    
        self.pushButton_1.clicked.connect(
            self.search
        )

        self.pushButton_2.clicked.connect(
            self.save
        )

        self.pushButton_2.clicked.connect(
            self.clear_fil
        )

        self.pushButton_3.clicked.connect(
           self.delete
        )

        self.pushButton_3.clicked.connect(
           self.clear_fil
        )
        
        

        self.retranslateUi(bibl)
        QtCore.QMetaObject.connectSlotsByName(bibl)

        self.loaddata()



    def retranslateUi(self, bibl):
        _translate = QtCore.QCoreApplication.translate
        bibl.setWindowTitle(_translate("bibl", "Каталог книг"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("bibl", "Инвентарный \nномер"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("bibl", "Название"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("bibl", "Жанр"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("bibl", "Год издания"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("bibl", "Автор"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("bibl", "Издательство"))
        item = self.tableWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("bibl", "Количество"))
        self.radioButton_1.setText(_translate("bibl", "Название"))
        self.radioButton_2.setText(_translate("bibl", "Жанр"))
        self.radioButton_3.setText(_translate("bibl", "Автор"))
        self.pushButton_1.setText(_translate("bibl", "Поиск"))
        self.pushButton_2.setText(_translate("bibl", "Добавить книгу"))
        self.pushButton_3.setText(_translate("bibl", "Удалить книгу"))
        self.label_5.setText(_translate("bibl", "Издательство"))
        self.label_2.setText(_translate("bibl", "Жанр"))
        self.label_4.setText(_translate("bibl", "Автор"))
        self.label_6.setText(_translate("bibl", "Количество"))
        self.label_3.setText(_translate("bibl", "Год издания"))
        self.label_1.setText(_translate("bibl", "Название"))
        self.label_7.setText(_translate("bibl", "Найти книгу по"))
        self.radioButton_4.setText(_translate("bibl", "Инвентарный номер"))








if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bibl = QtWidgets.QWidget()
    ui = Ui_bibl()
    ui.setupUi(bibl)
    bibl.show()
    sys.exit(app.exec_())
