# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chit_bil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#import pyodbc
import sqlite3


class Ui_chit(object):

    def loaddata(self):
        connection = sqlite3.connect('bibla.db')
        qur = "SELECT * FROM ticket"
        result = connection.execute(qur)
        
        self.tableWidget_1.setRowCount(1)
        for row_number, row_data in enumerate(result):
            self.tableWidget_1.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget_1.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
        connection.close()


    def loaddata_2(self):
        connection = sqlite3.connect('bibla.db')
        qur = "SELECT [inv],[name] FROM books"
        result = connection.execute(qur)
        
        self.tableWidget_2.setRowCount(1)
        for row_number, row_data in enumerate(result):
            self.tableWidget_2.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget_2.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
        connection.close()


    def save(self):
        fam = self.lineEdit_1.text()
        name = self.lineEdit_7.text()
        otch = self.lineEdit_2.text()
        numt = self.lineEdit_3.text()
        numt = int(numt)
        datevyd = self.lineEdit_4.text()
        datevoz = self.lineEdit_5.text()
        inv = self.lineEdit_6.text()
        inv = int(inv)
        conn = sqlite3.connect('bibla.db')
        cursor = conn.cursor()
        ins = cursor.execute("INSERT INTO ticket (fam, name, otch, numt, datevyd, datevoz, inv) VALUES (?,?,?,?,?,?,?)",(fam, name, otch, numt, datevyd, datevoz, inv))
        conn.commit()
        self.tableWidget_1.update()
        self.tableWidget_1.setRowCount(0)
        self.loaddata()
        cursor.close()
        self.lineEdit_6.clear

    def clear_fil(self):
        self.lineEdit_1.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()

    def delete(self):
        inv = self.lineEdit_6.text()
        inv = int(inv)
        fam = self.lineEdit_1.text()
        conn = sqlite3.connect('bibla.db')
        cursor = conn.cursor()
        ins = cursor.execute("DELETE FROM ticket WHERE inv = ? and fam = ?",(inv,fam,))
        conn.commit()
        self.tableWidget_1.update()
        self.tableWidget_1.setRowCount(0)
        self.loaddata()
        cursor.close()
        self.lineEdit_6.clear()
        self.lineEdit_1.clear()


    def setupUi(self, chit):
        chit.setObjectName("chit")
        chit.setEnabled(True)
        chit.resize(1000, 350)
        chit.setMinimumSize(QtCore.QSize(1000, 350))
        chit.setMaximumSize(QtCore.QSize(1000, 350))
        chit.setMouseTracking(False)
        chit.setTabletTracking(False)
        chit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        chit.setAcceptDrops(False)
        self.tableWidget_1 = QtWidgets.QTableWidget(chit)
        self.tableWidget_1.setGeometry(QtCore.QRect(10, 10, 731, 165))
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(7)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, item)
        self.tableWidget_1.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget_1.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_1.verticalHeader().setMinimumSectionSize(23)
        self.tableWidget_1.verticalHeader().setVisible(False)
        self.tableWidget_2 = QtWidgets.QTableWidget(chit)
        self.tableWidget_2.setGeometry(QtCore.QRect(760, 10, 230, 165))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.pushButton_1 = QtWidgets.QPushButton(chit)
        self.pushButton_1.setGeometry(QtCore.QRect(310, 310, 141, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(chit)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 310, 141, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setToolTip("Чтобы удалить введите фамилию и инвентарный номер")
        self.pushButton_2.setToolTipDuration(0)
        self.pushButton_3 = QtWidgets.QPushButton(chit)
        self.pushButton_3.setGeometry(QtCore.QRect(465, 370, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayoutWidget = QtWidgets.QWidget(chit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 220, 971, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 5, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 6, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 6, 1, 1)


        header = self.tableWidget_1.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header1 = self.tableWidget_2.horizontalHeader()
        header1.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header1.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)

        
        self.pushButton_1.clicked.connect(
            self.save 
        )

        self.pushButton_1.clicked.connect(
            self.clear_fil 
        )

        self.pushButton_2.clicked.connect(
            self.delete
        )

        self.loaddata()
        self.loaddata_2()
        self.retranslateUi(chit)
        QtCore.QMetaObject.connectSlotsByName(chit)

    def retranslateUi(self, chit):
        _translate = QtCore.QCoreApplication.translate
        chit.setWindowTitle(_translate("chit", "Читательский билет"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("chit", "Фамилия"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("chit", "Имя"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("chit", "Отчество"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("chit", "Номер билета"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("chit", "Дата выдачи"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("chit", "Дата возврата"))
        item = self.tableWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("chit", "Инвентарный\nномер"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("chit", "Инвентарный\nномер"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("chit", "Название"))
        self.pushButton_1.setText(_translate("chit", "Добавить запись"))
        self.pushButton_2.setText(_translate("chit", "Удалить запись"))
        self.pushButton_3.setText(_translate("chit", "Меню"))
        self.label.setText(_translate("chit", "Фамилия"))
        self.label_2.setText(_translate("chit", "Имя"))
        self.label_3.setText(_translate("chit", "Отчество"))
        self.label_4.setText(_translate("chit", "Номер билета"))
        self.label_5.setText(_translate("chit", "Дата выдачи"))
        self.label_6.setText(_translate("chit", "Дата возврата"))
        self.label_7.setText(_translate("chit", "Инвентарный номер"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chit = QtWidgets.QWidget()
    ui = Ui_chit()
    ui.setupUi(chit)
    chit.show()
    sys.exit(app.exec_())
